//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Elegant.Ui.CommandSourceAttribute("Server_Creation_Tool.ApplicationCommands", "Server_Creation_Tool.ApplicationCommands")]

namespace Server_Creation_Tool
{
    //  This class is required for commands suppport.
// Do not modify this code inside the editor.

public class ApplicationCommands
    {
    }
}