//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_Creation_Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("english")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastSavedSteamCMDLoc {
            get {
                return ((string)(this["lastSavedSteamCMDLoc"]));
            }
            set {
                this["lastSavedSteamCMDLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./7days/ +app_update 294420 validate")]
        public string daysInstallCmd {
            get {
                return ((string)(this["daysInstallCmd"]));
            }
            set {
                this["daysInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./css/ +app_update 232330 validate")]
        public string cssInstallCmd {
            get {
                return ((string)(this["cssInstallCmd"]));
            }
            set {
                this["cssInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./kf2/ +app_update 232130 validate")]
        public string kf2InstallCmd {
            get {
                return ((string)(this["kf2InstallCmd"]));
            }
            set {
                this["kf2InstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./sven/ +app_update 276060 validate")]
        public string svenInstallCmd {
            get {
                return ((string)(this["svenInstallCmd"]));
            }
            set {
                this["svenInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./ark/ +app_update 376030 validate")]
        public string arkInstallCmd {
            get {
                return ((string)(this["arkInstallCmd"]));
            }
            set {
                this["arkInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./csgo/ +app_update 740 validate")]
        public string csgoInstallCmd {
            get {
                return ((string)(this["csgoInstallCmd"]));
            }
            set {
                this["csgoInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./l4d/ +app_update 222840 validate")]
        public string l4dInstallCmd {
            get {
                return ((string)(this["l4dInstallCmd"]));
            }
            set {
                this["l4dInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./bo3/ +app_update 545990 validate")]
        public string codbo3InstallCmd {
            get {
                return ((string)(this["codbo3InstallCmd"]));
            }
            set {
                this["codbo3InstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./gmod/ +app_update 4020 validate")]
        public string gmodInstallCmd {
            get {
                return ((string)(this["gmodInstallCmd"]));
            }
            set {
                this["gmodInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./l4d2/ +app_update 222860 validate")]
        public string l4d2InstallCmd {
            get {
                return ((string)(this["l4d2InstallCmd"]));
            }
            set {
                this["l4d2InstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./cs/ +app_update 90 validate")]
        public string cs16InstallCmd {
            get {
                return ((string)(this["cs16InstallCmd"]));
            }
            set {
                this["cs16InstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./hurtworld/ +app_update 405100 validate")]
        public string hurtworldInstallCmd {
            get {
                return ((string)(this["hurtworldInstallCmd"]));
            }
            set {
                this["hurtworldInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./rust/ +app_update 258550 validate")]
        public string rustInstallCmd {
            get {
                return ((string)(this["rustInstallCmd"]));
            }
            set {
                this["rustInstallCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+login anonymous +force_install_dir ./synergy/ +app_update 17525 validate")]
        public string synergyInstallCmd {
            get {
                return ((string)(this["synergyInstallCmd"]));
            }
            set {
                this["synergyInstallCmd"] = value;
            }
        }
    }
}
