//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server_creation_tool.Server_data_files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _srvNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _srvNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server_creation_tool.Server_data_files._srvNames", typeof(_srvNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARK: Survival Evolved.
        /// </summary>
        internal static string ark {
            get {
                return ResourceManager.GetString("ark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeamNG.Drive.
        /// </summary>
        internal static string beamng {
            get {
                return ResourceManager.GetString("beamng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call of Duty: Black Ops 3.
        /// </summary>
        internal static string bo3 {
            get {
                return ResourceManager.GetString("bo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftopia.
        /// </summary>
        internal static string craftopia {
            get {
                return ResourceManager.GetString("craftopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Strike: 1.6.
        /// </summary>
        internal static string cs {
            get {
                return ResourceManager.GetString("cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Strike 2.
        /// </summary>
        internal static string cs2 {
            get {
                return ResourceManager.GetString("cs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Strike: Source.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days to die.
        /// </summary>
        internal static string days7 {
            get {
                return ResourceManager.GetString("days7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garry&apos;s Mod.
        /// </summary>
        internal static string gmod {
            get {
                return ResourceManager.GetString("gmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurtworld.
        /// </summary>
        internal static string hurtworld {
            get {
                return ResourceManager.GetString("hurtworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing Floor 2.
        /// </summary>
        internal static string kf2 {
            get {
                return ResourceManager.GetString("kf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left 4 Dead.
        /// </summary>
        internal static string l4d {
            get {
                return ResourceManager.GetString("l4d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left 4 Dead 2.
        /// </summary>
        internal static string l4d2 {
            get {
                return ResourceManager.GetString("l4d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Room In Hell.
        /// </summary>
        internal static string nmrih {
            get {
                return ResourceManager.GetString("nmrih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palworld.
        /// </summary>
        internal static string palworld {
            get {
                return ResourceManager.GetString("palworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rust.
        /// </summary>
        internal static string rust {
            get {
                return ResourceManager.GetString("rust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sven Coop.
        /// </summary>
        internal static string sven {
            get {
                return ResourceManager.GetString("sven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unturned.
        /// </summary>
        internal static string unturned {
            get {
                return ResourceManager.GetString("unturned", resourceCulture);
            }
        }
    }
}
